name = "Geb"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Geb"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc4"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso.git"
rev = "latest"

[[lean_lib]]
name = "Geb"
